version: '3.7'
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis


  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    container_name: kibana
    image: kibana:8.8.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  learning-app-network:
    driver: bridge