spring:
  application:
    name: learning_api
  data:
    mongodb:
      uri: mongodb+srv://zimb240:0908218507zimb240@cluster0.4emxftv.mongodb.net/learningDB?retryWrites=true&w=majority
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "590210671995-vqvohsa8ue8a0aljda9gp0hj3vfsduh9.apps.googleusercontent.com"
            client-secret: "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"
#            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            scope:
                  - email
                  - profile
                  - openid
security:
  jwt:
    accessTokenKey: YourAccessTokenKey
    refreshTokenKey: YourRefreshTokenKey